<?php

return [
    'codigo_modelo'              => 4,
    'area_geografica'            => 8,
    'sub_region_geografica'      => 9,
    'departamento'               => 10,
    'municipio_hallazgo'         => 11,
    'clasificacion_existente'    => 13,
    'confiabilidad_modelo'       => 14,
    'funcion_primaria'           => 17,
    'cronologia_alto'            => 21,
    'cronologia_alto_ac_dc'      => 22,
    'cronologia_bajo'            => 23,
    'cronologia_bajo_ac_dc'      => 24,
    'forma_base'                 => 42,
    'decoracion_1'               => 64,
    'decoracion_2'               => 65,
    'decoracion_3'               => 66,
    'tecnica_manufactura'        => 73,
    'tratamiento_superficie'     => 74,
    'acabado_superficie_externa' => 76,
    'textura_externa'            => 78,
    'min_nombre_munsell'         => 81,
    'max_nombre_munsell'         => 82,
    'ambiente_coccion_1'         => 84,
    'composicion_inorganica'     => 88,
    'composicion_organica'       => 89,
    'forma_granos'               => 90,
];
