<?php

return [

    'menus'                                          => [
        'Introducción'                                   => 1,
        'Aspectos Tecnológicos'                          => 2,
        'Aspectos Metodologicos Para Descripcion Vasija' => 6,
        'Elementos Que Conforman Una Vasija'             => 10,
        'Formas'                                         => 28,
        'Forma/Función'                                  => 51,
        'Acabado De La Superficie'                       => 69,
        'Decoración'                                     => 75,
        'Términos Complementarios'                       => 94,
        'Bibliografía'                                   => 96,
    ],
    'Aspectos Tecnológicos'                          => [
        'Terminos Generales'      => 3,
        'Técnicas De Manufactura' => 4,
        'Cocción'                 => 5,
    ],
    'Aspectos Metodologicos Para Descripcion Vasija' => [
        'Metodología Para La Descripción' => 7,
        'Partes Básicas De Una Vasija'    => 8,
        'Tipos De Vasija'                 => 9,
    ],
    'Elementos Que Conforman Una Vasija'             => [
        'Boca'                           => 11,
        'Borde (Direccion)'              => 12,
        'Borde (Morfologia)'             => 13,
        'Labio'                          => 14,
        'Cuello'                         => 15,
        'Hombro'                         => 16,
        'Cuerpo (De Forma Simple)'       => 17,
        'Cuerpo (De Forma Compuesta)'    => 18,
        'Cuerpo (De Formas Específicas)' => 19,
        'Fondo'                          => 20,
        'Base'                           => 21,
        'Soporte'                        => 22,
        'Asa'                            => 23,
        'Agarradera'                     => 24,
        'Mango'                          => 25,
        'Vertedera'                      => 26,
        'Tapa Y Tapon'                   => 27,
    ],
    'Formas'                                         => [
        'Placa'     => 29,
        'Budare'    => 30,
        'Plato'     => 31,
        'Sartén'    => 32,
        'Cuenco'    => 33,
        'Cazuela'   => 34,
        'Vaso'      => 35,
        'Taza'      => 36,
        'Copa'      => 37,
        'Cucharón'  => 38,
        'Olla'      => 39,
        'Tecomate'  => 40,
        'Mocasín'   => 41,
        'Alcarraza' => 42,
        'Jarra'     => 43,
        'Múcura'    => 44,
        'Cántaro'   => 45,
        'Ánfora'    => 46,
        'Botella'   => 47,
        'Botellón'  => 48,
        'Aríbalo'   => 49,
        'Barríl'    => 50,
    ],
    'Forma/Función'                                  => [
        'Urna'                           => 52,
        'Poporo'                         => 53,
        'Retablo'                        => 54,
        'Figurilla'                      => 55,
        'Sello'                          => 56,
        'Rodillo O Pintadera'            => 57,
        'Instrumento Musical (Aerófono)' => 58,
        'Instrumento Musical (Sonaja)'   => 59,
        'Volante De Huso'                => 60,
        'Rallador'                       => 61,
        'Colador'                        => 62,
        'Miniatura'                      => 63,
        'Cuenta'                         => 64,
        'Botella Silbato'                => 65,
        'Gacha'                          => 66,
        'Incensario'                     => 67,
        'Máscara'                        => 68,
    ],
    'Acabado De La Superficie'                       => [
        'Alisado' => 70,
        'Pulido'  => 71,
        'Bruñido' => 72,
        'Raspado' => 73,
        'Engobe'  => 74,
    ],
    'Decoración'                                     => [
        'Incisión'                       => 76,
        'Excisión'                       => 77,
        'Calado'                         => 78,
        'Grabado'                        => 79,
        'Hachurado'                      => 80,
        'Acanalado'                      => 81,
        'Impresión 1 (Con Dedo)'         => 82,
        'Impresión 2 (Ungulación)'       => 83,
        'Impresión 3 (Con Instrumentos)' => 84,
        'Impresión 4 (Con Sello)'        => 85,
        'Impresión 5 (Por Rotación)'     => 86,
        'Impresión 6 (De Mecedora)'      => 87,
        'Pintura'                        => 88,
        'Baño'                           => 89,
        'Ahumado'                        => 90,
        'Modelado'                       => 91,
        'Moldeado'                       => 92,
        'Aplicación'                     => 93,
    ],
    'Términos Complementarios'                       => [
        'General' => 95,
    ],
    'Bibliografía'                                   => [
        'General' => 97,
    ],

];
